-- 테이블 == DB == ArrayList<MemberDTO> == 배열리스트 == DAO의 멤버변수 datas 의미
CREATE TABLE MEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL
);

INSERT INTO MEMBER (MID,PASSWORD,NAME) VALUES('ADMIN','1234','관리자');
UPDATE MEMBER SET PASSWORD=? WHERE MID=?; -- 비밀번호 변경
DELETE FROM MEMBER WHERE MID=?; -- 회원탈퇴

SELECT MID,PASSWORD,NAME FROM MEMBER WHERE MID=?; --아이디중복확인
SELECT MID,PASSWORD,NAME FROM MEMBER WHERE MID=? AND PASSWORD=?;-- 로그인

DROP TABLE MEMBER;

select * FROM MEMBER;