CREATE TABLE STUDENT(
	NUM INT PRIMARY KEY, -- 학생 번호
	NAME VARCHAR(15) NOT NULL, -- 이름
	SCORE INT DEFAULT 0, -- 점수
	POS VARCHAR(10) NOT NULL, -- 포지션(동아리 이름 같은 개념)
	LV INT DEFAULT 5 -- 레벨(등급 같은 개념)
);
INSERT INTO STUDENT (NUM,NAME,POS) VALUES(1,'티모','탑');
INSERT INTO STUDENT (NUM,NAME,SCORE,POS) VALUES(2,'아리',80,'미드');
INSERT INTO STUDENT (NUM,NAME,SCORE,POS,LV) VALUES(3,'아무무',82,'서포터',6);
INSERT INTO STUDENT (NUM,NAME,SCORE,POS,LV) VALUES(4,'모르가나',73,'서포터',7);
INSERT INTO STUDENT (NUM,NAME,SCORE,POS,LV) VALUES(5,'오리아나',24,'미드',8);
INSERT INTO STUDENT (NUM,NAME,SCORE,POS,LV) VALUES(6,'에코',13,'정글',9);
INSERT INTO STUDENT (NUM,NAME,SCORE,POS,LV) VALUES(7,'이즈리얼',45,'바텀',10);
INSERT INTO STUDENT (NUM,NAME,POS) VALUES(8,'그웬','탑');
INSERT INTO STUDENT (NUM,NAME,POS) VALUES(9,'이렐리아','탑');
INSERT INTO STUDENT (NUM,NAME,POS,SCORE) VALUES(10,'잭스','탑',50);
INSERT INTO STUDENT (NUM,NAME,POS,LV) VALUES(11,'말파이트','탑',6);
INSERT INTO STUDENT (NUM,NAME,POS) VALUES(12,'진','바텀');
SELECT * FROM STUDENT;
DROP TABLE STUDENT;

-- Q8. 학생 테이블에서 이름, 포지션 열만 검색
SELECT NAME, POS FROM STUDENT;
-- Q9. 학생 DB 에서 번호가 6 이하이면서, 점수가 20 점 초과이면서, 포지션이 정글, 바텀, 서포터인 목록을 출력
SELECT NUM,NAME,SCORE,POS,LV FROM STUDENT WHERE NUM<=6 AND SCORE>20 AND POS IN('정글','바텀','서포터');
-- Q10. 포지션 열이 탑인 데이터 중에 점수 열이 50 점 미만인 데이터를 검색해서 레벨 오름차순으로 정렬하고, 같은 레벨일 경우 번호가 높은 순으로 출력
SELECT NUM,NAME,SCORE,POS,LV FROM STUDENT WHERE POS ='탑' AND SCROE<50 ORDER BY LV ASC, NUM DESC;
-- Q11. 이름에 '아'를 포함하는 목록을 출력
SELECT NUM,NAME,SCORE,POS,LV FROM STUDENT WHERE NAME LIKE '%아%';
-- Q12. 포지션들을 중복없이 출력해주세요.
SELECT DISTINCT POS FROM STUDENT;
-- Q13. 포지션이 탑인 학생의 수를 '탑 총 인원'이라는 별칭으로 출력해주세요.
SELECT COUNT(*) AS "탑 총 인원" FROM STUDENT WHERE POS ='탑';
-- Q14. 이름이 티모인 학생의 포지션을 서포터로 바꿔주세요.
UPDATE STUDENT SET POS ='서포터' WHERE NAME ='티모';
-- Q15. 레벨이 6이하인 학생들을 모두 학생부에서 지워주세요.
DELETE FROM STUDENT WHERE LV<=6;
